### ISSUE TITLE
Userchrome not working

### ISSUE THREAD

**Issue by sethothewetho** [Naezr/ShyFox#123]
Sorry, I don't know what the issue is, but I thought that I would put it here.
Userchrome doesn't seem to be working. I have had it working for a month or so now, but now I can't hide the side bar.

I have tried reinstalling it, and follow the instructions.

What should I do?

**Comment by Naezr** [comment]
You need to update ShyFox and re-configure Userchrome Toggle

**Comment by sethothewetho** [comment]
So, I downloaded the latest version, and swapped the chrome folder. I reset and reconfigured the userchrome settings but it still hasn't fixed it.

**Comment by leakspin** [comment]
The problem is that, in the screenshots, you haven't inserted the prefixes used for each style (the "=", "+" symbols), so no style will be applied to the theme.

**Comment by sethothewetho** [comment]
> You need to update ShyFox and re-configure Userchrome Toggle

So I reinstalled ShyFox, reset and imported sideberry settings, and reset and reconfigured userchrome settings. It still doesn't work.

**Comment by Naezr** [comment]
The new Userchrome Toggle use invisible characters instead of -=+? ShyFox is also updated to use them.

**Comment by xx90three** [comment]
![Screenshot 2024-06-13 201705](https://github.com/user-attachments/assets/56f97234-4810-4501-838e-d4ece28c4bc1)
Everything disappeared. I can't click on the Nav bar and it won't hide either. Also Userchrome Toggle doesn't work. Everything broke for me after updating. Not sure what I'm doing wrong.

**Comment by Naezr** [comment]
> Everything broke for me after updating

It looks like you have clean mode enabled. Press ctrl+alt+X or ctrl+shift+4

**Comment by xx90three** [comment]
> It looks like you have clean mode enabled. Press ctrl+alt+X or ctrl+shift+4

That's it. I'm dumb. Thank you!

**Comment by Naezr** [comment]
> I'm dumb.

I'm partly to blame for that, too. I released an update for Userchrome Toggle that is not compatible with the old ShyFox and updated ShyFox for compatibility. Due to extensions being updated automatically, people are forced to update because everything stopped working

**Comment by sethothewetho** [comment]
Should I try uninstalling and reinstalling firefox?

**Comment by Naezr** [comment]
Well, if you want to, reinstall it. I don't know.

**Comment by unitythemaker** [comment]
I deleted my chrome folder in profile root and re-copied, reset sideberry settings and re-imported, re-install Userchrome Toggle Extended, tried a few different themes, restarted Firefox but I still can't use the shortcuts, manually toggling items by clicking Userchrome Toggle Extended extension in toolbar also didn't work. What am I doing wrong?

**Comment by Naezr** [comment]
> re-copied

Where do you copy files from? Are you sure you downloaded the latest ones?

**Comment by mr13tech** [comment]
> I deleted my chrome folder in profile root and re-copied, reset sideberry settings and re-imported, re-install Userchrome Toggle Extended, tried a few different themes, restarted Firefox but I still can't use the shortcuts, manually toggling items by clicking Userchrome Toggle Extended extension in toolbar also didn't work. What am I doing wrong?

I have tried same and got same problems.

**Comment by Naezr** [comment]
If you click on the toggles in the extension but the styles don't change, then you have an old version of ShyFox that is not compatible with the new Userchrome Toggle

**Comment by mr13tech** [comment]
working for me now; tyvm

**Comment by unitythemaker** [comment]
I was able to fix it by re-installing my profile.

Steps I did (all extensions will be uninstalled and you will get logged out from most websites):
- Go to ``about:profiles``
- Click on ``Restart with Add-ons Disabled...``
- It will ask something, click on ``Refresh``
- All extensions will be uninstalled and you will be put in safe mode
- Open Firefox menu, click on Help, disable Troubleshoot mode
- You will be able to install extensions now
- Follow install shyfox steps

**Comment by unitythemaker** [comment]
Unsure but this might be also fixed by clearing Firefox cache. (Deleting the path ``Local Directory`` in about:profiles)
